//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "project_members_role")]
pub enum ProjectMembersRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "developer")]
    Developer,
    #[sea_orm(string_value = "viewer")]
    Viewer,
}
