//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "project_repository_status"
)]
pub enum ProjectRepositoryStatus {
    #[sea_orm(string_value = "connected")]
    Connected,
    #[sea_orm(string_value = "disconnected")]
    Disconnected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "project_respository_auth_type"
)]
pub enum ProjectRespositoryAuthType {
    #[sea_orm(string_value = "none")]
    None,
    #[sea_orm(string_value = "pat")]
    Pat,
}
