//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "deployment_status")]
pub enum DeploymentStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "building")]
    Building,
    #[sea_orm(string_value = "deploying")]
    Deploying,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "success")]
    Success,
}
