//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "project_runtime")]
pub enum ProjectRuntime {
    #[sea_orm(string_value = "node_js")]
    NodeJs,
    #[sea_orm(string_value = "python")]
    Python,
    #[sea_orm(string_value = "go")]
    Go,
    #[sea_orm(string_value = "static")]
    Static,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "project_status")]
pub enum ProjectStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "archived")]
    Archived,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "project_types")]
pub enum ProjectTypes {
    #[sea_orm(string_value = "files")]
    Files,
    #[sea_orm(string_value = "repo")]
    Repo,
}
