//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::organization_invitations::Entity as OrganizationInvitations;
pub use super::organization_members::Entity as OrganizationMembers;
