//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "organization_invitations_status"
)]
pub enum OrganizationInvitationsStatus {
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "organization_member_role"
)]
pub enum OrganizationMemberRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "editor")]
    Editor,
    #[sea_orm(string_value = "viewer")]
    Viewer,
    #[sea_orm(string_value = "owner")]
    Owner,
}
