//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "unverified")]
    Unverified,
    #[sea_orm(string_value = "disabled")]
    Disabled,
    #[sea_orm(string_value = "suspended")]
    Suspended,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
