//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "project_environment_variables_environment"
)]
pub enum ProjectEnvironmentVariablesEnvironment {
    #[sea_orm(string_value = "development")]
    Development,
    #[sea_orm(string_value = "production")]
    Production,
    #[sea_orm(string_value = "staging")]
    Staging,
}
